services:
  web:
    build: .
    container_name: kisekae-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped

volumes:
  static_volume: